baseURL = "https://tycharlie.com/"
title = "Charlie's Playground"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
googleAnalytics = "G-H5V684XBH8"
enableRobotsTXT = true
disqusShortname = "tycharlie"
