mainSections = [ "posts" ]
featuredImageField = "image"
rssFullContent = true
favicon = "/icons/favicon.svg"

[Sidebar]
    subtitle = "Keep learning"
    compact = false
    emoji = "" 
    [Sidebar.avatar]
        enable = true
        local = true
        src = "img/avatar.webp"

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"
    [widgets.homepage.params]
    limit = 10

[[widgets.homepage]]
type = "categories"
    [widgets.homepage.params]
    limit = 10

[[widgets.homepage]]
type = "tag-cloud"
    [widgets.homepage.params]
    limit = 20

[[widgets.page]]
type = "toc"

[Comments]
enabled = true
provider = "disqus"
# disqusShortname is placed at root section

[Footer]
since = 2023
customText = ""

[Article]
toc = true
readingTime = true
math = true
    [Article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

[DateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006"

[opengraph.twitter]
    site = "" # twitter name without @
    card = "summary_large_image"

[defaultImage.opengraph]
    enabled = true
    local = true
    src = "/img/avatar.webp"

[colorScheme]
    toggle = true
    default = "dark"

[imageProcessing.cover]
    enabled = true
[imageProcessing.content]
    enabled = true
