baseURL: 'https://tycharlie.com/'
languageCode: 'en-us'
title: "Charlie's Playground"
DefaultContentLanguage: en

sitemap:
  changeFreq: always
  filename: sitemap.xml
  priority: 0.5

googleAnalytics: G-H5V684XBH8

enableRobotsTXT: true

disqusShortname: "tycharlie"

languages:
  en:
    languageName: "English"
  zh-tw:
    languageName: "繁體中文"

module:
  imports:
    path: github.com/CaiJimmy/hugo-theme-stack/v3

Params:
  favicon: "/icons/favicon.svg"
  mainSections: 
    - post
  Sidebar:
    # emoji: "👨🏻‍💻"
    subtitle: Travel in the coding world
    compact: false
    avatar:
      enable: true
      local: true
      src: img/avatar.png
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 10
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 20
    page:
      - type: toc
  Comments:
    enabled: true
    provider: disqus
    # provider: remark42
    # remark42:
    #   host: https://comment.tycharlie.com
    #   site: tycharlie.com
    #   locale: en
  Footer:
    since: 2023
    customText: ""
  Article:
    toc: true
    readingTime: true
    math: true
  DateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -100
      params:
        icon: home
    - identifier: about
      name: About
      url: /about
      weight: -90
      params:
        icon: user

  Social:
    - identifier: github
      name: GitHub
      url: 'https://github.com/jkcharlie6679/'
      params:
        icon: brand-github
        newTab: true
    - identifier: gitlab
      name: Gitlab
      url: 'https://gitlab.com/jkcharlie6679/'
      params:
        icon: brand-gitlab
        newTab: true
    - identifier: linkedin
      name: linkedin
      url: 'https://www.linkedin.com/in/tsungyu-chan/'
      params:
        icon: brand-linkedin
        newTab: true
